stages:
  - test
  - build
  - deploy
  - cleanup

test_api_dev:
  stage: test
  image: node:6
  services:
    - mongo
  script:
    - npm install --silent
    - node_modules/.bin/tape app/tests/*/*.test.js | node_modules/.bin/tap-spec
  only:
    - develop

build_image_dev:
  stage: build
  image: gitlab/dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN git.esn.org:4567
    - docker build --file="app/Dockerfile.prod" -t git.esn.org:4567/sturgelose/esnhapi:dev .
    - docker push git.esn.org:4567/sturgelose/esnhapi:dev
  only:
    - develop

deploy_dev:
  stage: deploy
  image: monostream/rancher-compose
  script:
    - cd rancher/development
    - rancher-compose -p ESNhapi up --upgrade --pull --force-upgrade -d API
  only:
    - develop

cleanup_fail_build_job:
  stage: cleanup
  image: monostream/rancher-compose
  script:
    - cd rancher/development
    - rancher-compose -p ESNhapi up --upgrade --rollback -d API
  when: on_failure
  only:
    - develop

cleanup_success_build_job:
  stage: cleanup
  image: monostream/rancher-compose
  script:
    - cd rancher/development
    - rancher-compose -p ESNhapi up --upgrade --pull --confirm-upgrade -d API
  when: on_success
  only:
    - develop


