version: '2'
services:
    api:
        build:
          context: .
          dockerfile: app/Dockerfile
        volumes:
         - "./app:/src/app"
        ports:
         - "3000:3000"
         - "5858:5858"
        links:
         - db:mongo
    db:
        image: mongo
        ports:
         - "27017:27017"
        volumes:
         - "./data/mongo/configdb:/data/configdb"
         - "./data/mongo/db:/data/db"
