version: '2'
services:
    api:
      build:
        context: .
        dockerfile: Dockerfile.prod
      image: git.esn.org:4567/sturgelose/esnhapi:v1
      ports:
        - "3000:3000"
    db:
        image: mongo
