version: '2'
services:
    api:
      container_name: esnhapi_test_api
      build:
        context: .
        dockerfile: app/Dockerfile.test
      tty: true
      ports:
        - "3000:3000"
      volumes:
           - "./app:/src/app/"
           - "./test:/src/test/"
      links:
        - mongo:mongo
    mongo:
        container_name: esnhapi_test_db
        image: mongo
        ports:
         - "27017:27017"
        tty: true
