build_image:
  image: docker:git
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN git.esn.org:4567
    - docker build --file="Dockerfile.prod" -t git.esn.org:4567/sturgelose/esnhapi .
    - docker push git.esn.org:4567/sturgelose/esnhapi:dev
  only:
    - develop
